#! /bin/sh
#
#
# Test known data
#
echo 1. Test predefine data file dumps against known correct results
#
rm -f results
#
./tst > results
diff -s results correctResults
#
#
# Test some randomly generated data
#
#
echo 2. Test random file data by comparing ihad output against at least od output
#
# echo Small file of 123 random bytes
./randomDataTest 123
#
echo Medium file of 12345 random bytes
./randomDataTest 12345
#
echo Larger file of 23454321 random bytes
./randomDataTest 23454321
#
